repos:
- repo: meta
  hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.3.1
  hooks:
    - id: check-github-workflows
- repo: https://github.com/python/black
  rev: 21.5b1
  hooks:
    - id: black
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
    - id: isort
      # explicitly pass settings file so that isort does not try to deduce
      # which settings to use based on a file's directory
      args: ["--settings-path", ".isort.cfg"]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.17.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==21.4.3']
